Assembler
bernie-g/Techarium pull request #74
Opened 2021-07-26 16:39 UTC by Lazzzzz

2021-07-26 17:25 UTC, agnor99 requested changes

2021-07-26 18:00 UTC, agnor99 requested changes

2021-07-26 18:00 UTC, agnor99 commented on src/main/java/software/bernie/techarium/display/container/AssemblerContainer.java
> +		this.addSlot(new WhiteListItemSlot(tile, 9, 4, 37, List.of(new ItemStack(AssemblerTile.boxItem))));
```suggestion
		this.addSlot(new WhiteListItemSlot(tile, 9, 4, 37, new ItemStack(BlockRegistry.BOX_BLOCK.get())));
```
remove AssemblerTile.boxItem and use the direct RegistryObjectReference instead

2021-07-26 18:00 UTC, agnor99 commented on src/main/java/software/bernie/techarium/display/container/component/WhiteListItemSlot.java
> +	public WhiteListItemSlot(IInventory inv, int id, int posX, int posY, List<ItemStack> whitelist) {
```suggestion
	public WhiteListItemSlot(IInventory inv, int id, int posX, int posY, ItemStack... whitelist) {
```
Make whitelist a varargs paramer

2021-07-26 18:00 UTC, agnor99 commented on src/main/java/software/bernie/techarium/datagen/TechariumBlockStateProvider.java
> +        //simpleBlockAndItem(BlockRegistry.BOX_BLOCK.get(), models().modLoc("block/default_box_side"), models().modLoc("block/default_box_top"));
remove commented code if not neccessary

2021-07-26 18:00 UTC, agnor99 commented on src/main/java/software/bernie/techarium/display/container/AssemblerContainer.java
> +    		if (moveItemStackTo(stack, 0, 36, false)) return true;
imo the return should be on the next line, tabbed in for better readability

2021-07-26 18:00 UTC, agnor99 commented on src/main/java/software/bernie/techarium/display/screen/AssemblerContainerScreen.java
> +    private static final IDrawable BACKGROUND_TEXTURE = new UiTexture(new ResourceLocation(ModID, "textures/gui/assembler/assembler.png"), 201, 195).getFullArea();
Move to software.bernie.techarium.client.screen.draw.GuiAddonTextures

2021-07-26 18:00 UTC, agnor99 commented on src/main/java/software/bernie/techarium/recipe/recipe/assembler/AssemblerRecipeHelper.java
> +	private static enum RESULT {
enums are always static
rename to Result because it's a class

2021-07-26 18:00 UTC, agnor99 commented on src/main/java/software/bernie/techarium/registry/RecipeRegistry.java
> +    public static IRecipeType<AssemblerRecipe> ASSEMBLER_RECIPE_TYPE = IRecipeType.register("techarium:assembleur");
fix typo assembleur -> assembler

2021-07-26 18:00 UTC, agnor99 commented on src/main/java/software/bernie/techarium/tile/assembler/AssemblerTile.java
> +		if (count >= stack.getCount())
use {} for if else

2021-07-26 18:00 UTC, agnor99 commented on src/main/java/software/bernie/techarium/tile/assembler/AssemblerTile.java
> +	private enum CRAFTING_TYPE {
rename to CraftinType because it's a classname

2021-07-26 18:09 UTC, agnor99 commented on src/main/java/software/bernie/techarium/tile/assembler/AssemblerTile.java
> +		List<ICraftingRecipe> recipies = level.getRecipeManager().getAllRecipesFor(IRecipeType.CRAFTING);
fix type:
recipies -> recipes
recipie -> recipe

2021-07-26 19:08 UTC, agnor99 commented on src/main/java/software/bernie/techarium/display/container/component/WhiteListItemSlot.java
> +
Maybe Arrays.asList(itemStacks)

2021-07-26 19:09 UTC, Lazzzzz commented on src/main/java/software/bernie/techarium/display/container/component/WhiteListItemSlot.java
> +
True my bad

2021-07-26 19:10 UTC, agnor99 requested changes

2021-07-26 19:10 UTC, agnor99 commented on src/main/java/software/bernie/techarium/tile/assembler/AssemblerTile.java
> +			output = lookForCraftingrecipes ();
remove space

2021-07-26 19:10 UTC, agnor99 commented on src/main/java/software/bernie/techarium/tile/assembler/AssemblerTile.java
> +		List<ICraftingRecipe> recipes  = level.getRecipeManager().getAllRecipesFor(IRecipeType.CRAFTING);
remove space

2021-07-26 19:10 UTC, agnor99 commented on src/main/java/software/bernie/techarium/tile/assembler/AssemblerTile.java
> +		for (ICraftingRecipe recipe : recipes ) {
remove space

2021-07-26 19:10 UTC, agnor99 commented on src/main/java/software/bernie/techarium/tile/assembler/AssemblerTile.java
> +	private enum CraftinType {
fix typo: CraftinType -> CraftingType

2021-07-26 19:12 UTC, agnor99 commented on src/main/java/software/bernie/techarium/tile/assembler/AssemblerTile.java
> +	private enum CRAFTING_TYPE {
I've spelled it wrong, my bad

2021-07-27 15:59 UTC, agnor99 requested changes
Remove unused imports in 
AssemblerTile, AssemblerRenderer, AssemblerRecipeHelper, AssemblerContainer

2021-12-25 22:05 UTC, closed without merging