[WIP] Machine Render in GUI
bernie-g/Techarium pull request #90
Opened 2021-09-05 22:51 UTC by OneLemonyBoi

2021-09-12 07:18 UTC, bernie-g approved these changes

2021-09-12 07:18 UTC, bernie-g commented on src/main/java/software/bernie/techarium/trait/item/ItemBehaviours.java
> +                event.getController().setAnimation(new AnimationBuilder().addAnimation("Botarium.anim.idle", true));
Can we add a helper method for this instead of copy pasting this everywhere?

2021-09-12 07:18 UTC, bernie-g commented on src/main/java/software/bernie/techarium/trait/item/ItemBehaviours.java
> +                    Utils.rl("geo/magneticcoil/magneticcoil.geo.json"),
Pretty sure we could just reuse the actual tile model and not have to use a new one

2021-09-17 14:41 UTC, agnor99 requested changes

2021-09-17 14:41 UTC, agnor99 commented on src/main/java/software/bernie/techarium/util/Utils.java
> +    }
Use Techarium.rl instead

2021-09-22 16:32 UTC, agnor99 approved these changes

2021-09-22 16:41 UTC, merged